### ISSUE TITLE
请问大佬可不可以将数据库端也单独部署呢

### ISSUE THREAD

**Issue by jonezj** [testnet0/testnet#12]

**Comment by testnet0** [comment]
支持单独部署，可以自己搭建一个mysql数据库导入db/testnet.sql,然后修改docker-compose.yml里的数据库连接地址和密码就可以

**Comment by jonezj** [comment]
> 支持单独部署，可以自己搭建一个mysql数据库导入db/testnet.sql,然后修改docker-compose.yml里的数据库连接地址和密码就可以

好的感谢大佬
