### ISSUE TITLE
大佬资产测绘功能中点击一键导入没反应，还有我想问一下怎么选择节点进行扫描呢

### ISSUE THREAD

**Issue by jonezj** [testnet0/testnet#13]

**Comment by jonezj** [comment]
大佬我那个任务列表中任务策略论询不管用只有指定能用怎么办呢

**Comment by testnet0** [comment]
资产导入没有反应指的是什么？最好附上截图。
解释一下任务分配策略，轮询指的是所有在线的节点，轮流执行任务，按照配置的并发数量分配，可以在节点管理-节点配置修改每个节点的任务并发数量
指定是可以选择一个节点去执行

**Comment by jonezj** [comment]
> 资产导入没有反应指的是什么？最好附上截图。 解释一下任务分配策略，轮询指的是所有在线的节点，轮流执行任务，按照配置的并发数量分配，可以在节点管理-节点配置修改每个节点的任务并发数量 指定是可以选择一个节点去执行

我试了几次就特殊的资产无法导入，这个是做限制了吗大佬

**Comment by jonezj** [comment]
而且特殊的资产也无法跑子域名什么的，这个怎么解除限制啊大佬

**Comment by testnet0** [comment]
看下资产管理-黑名单
