### ISSUE TITLE
安装过程中报错read tcp XXX:44676->124.160.145.45:80: read: connection reset by peer

### ISSUE THREAD

**Issue by Gak1** [testnet0/testnet#15]
安装过程总报错如下
[root@linux testnet]# docker compose up -d
[+] Running 11/4
 ⠙ testnet-es 9 layers [⣿⣿⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                          57.2s
 ⠹ testnet-mysql 10 layers [⣿⠀⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulling                                                                                     57.2s
 ⠙ testnet-client 13 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                 57.2s
 ⠙ testnet-frontend 11 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                 57.2s
read tcp XXX:44676->124.160.145.45:80: read: connection reset by peer

直接访问124.160.145.45提示无权限相关报错
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Anonymous access is forbidden for this operation.</Message>
<RequestId>66D84BDB5BE4553230BC7CBB</RequestId>
<HostId>124.160.145.45</HostId>
<EC>0003-00001201</EC>
<RecommendDoc>https://api.aliyun.com/troubleshoot?q=0003-00001201</RecommendDoc>
</Error>

![Snipaste_2024-09-04_20-01-29](https://github.com/user-attachments/assets/f567a83a-5c52-4f7c-b050-40b135297e1d)

**Comment by testnet0** [comment]
如果是国外的机器建议不使用加速

**Comment by Gak1** [comment]
是国内的，不过试了关闭加速之后可以成功安装部署了，感谢大佬
