### ISSUE TITLE
对IP使用masscan，任务失败或结果无法更新到端口信息中

### ISSUE THREAD

**Issue by nonetail22** [testnet0/testnet#18]
部署最新版
手动建立项目，公司
手动批量导入主域名，子域名
使用DNS解析，对子域名进行解析，可以正常更新信息到IP列表
对IP使用masscan，在工作流中提示无法找到结果文件
进入client，直接运行报错的命令，提示找不到masscan
把masscan复制到/usr/bin中，手动执行命令，或者在页面上执行任务都可以成功执行，但是在端口信息中没有更新内容

**Comment by testnet0** [comment]
提示找不到masscan是因为没有在节点管理-工具管理里安装masscan

> 部署最新版 手动建立项目，公司 手动批量导入主域名，子域名 使用DNS解析，对子域名进行解析，可以正常更新信息到IP列表 对IP使用masscan，在工作流中提示无法找到结果文件 进入client，直接运行报错的命令，提示找不到masscan 把masscan复制到/usr/bin中，手动执行命令，或者在页面上执行任务都可以成功执行，但是在端口信息中没有更新内容

**Comment by testnet0** [comment]
没有端口信息可以去工作流管理-任务列表查看执行日志是否有异常

**Comment by nonetail22** [comment]
> 没有端口信息可以去工作流管理-任务列表查看执行日志是否有异常
执行日志中没有异常，也提示更新资产成功，但是端口信息就是没有在端口页面显示

**Comment by nonetail22** [comment]
查看了数据库，asset_port中没有更新信息

**Comment by nonetail22** [comment]
确实是没有安装，手动安装后，masscan依旧不能更新端口信息，使用nmap可以了。多谢
