### ISSUE TITLE
第三方集成能考虑加入飞书集成吗

### ISSUE THREAD

**Issue by w990222** [testnet0/testnet#22]
![image](https://github.com/user-attachments/assets/46e471ce-7646-450e-9ff8-4fc308073f07)

**Comment by testnet0** [comment]
你好，是想要实现什么需求，现在是支持飞书机器人发送通知

**Comment by w990222** [comment]
> 你好，是想要实现什么需求，现在是支持飞书机器人发送通知

这个目前够用，有完整的手册吗，我看wiki中有些配置项像AI接口什么的还没有

**Comment by testnet0** [comment]
文档还在迁移中，可以先看下这个文档：https://m55giu8f62.feishu.cn/wiki/RYg5wB880iRL2oknCqXcsWL2nRe
