### ISSUE TITLE
bug:添加子域名时，确认提交会报错，刷新页面又发现子域名添加成功

### ISSUE THREAD

**Issue by w990222** [testnet0/testnet#23]
![image](https://github.com/user-attachments/assets/b0b5e152-b81e-4acc-9ce8-46976c20fb24)
![image](https://github.com/user-attachments/assets/7c0337c6-e796-4058-b842-5b62b4f46991)

**Comment by testnet0** [comment]
同一个项目下子域名不能重复，应该是你已经录入了

**Comment by w990222** [comment]
> 同一个项目下子域名不能重复，应该是你已经录入了

我第一次输入就报错

**Comment by testnet0** [comment]
是因为IP输入的格式不正确导致报错,后续会优化提示文案
