### ISSUE TITLE
高级查询问题

### ISSUE THREAD

**Issue by li-kangwen** [testnet0/testnet#25]
当高级查询字段为空时，不能准确查到数据，会一直在响应
![IMG20241118-152000733](https://github.com/user-attachments/assets/735ec6d5-0099-4b6f-9658-1ec288d65928)
<img width="409" alt="mx_screencap_20241118_152137" src="https://github.com/user-attachments/assets/0318075a-c2f3-42f0-b820-635d3f175b94">

**Comment by testnet0** [comment]
问题已记录

**Comment by whoisavicii** [comment]
高级查询感觉需要加一个任务执行结果查询列？ 比如成功\失败

**Comment by testnet0** [comment]
已修复
