### ISSUE TITLE
httpx 报错

### ISSUE THREAD

**Issue by gslsf223** [testnet0/testnet#28]
系统报错信息：
![image](https://github.com/user-attachments/assets/c614d515-e108-44f5-8201-454a06d751ef)

人为执行报错如下：
![image](https://github.com/user-attachments/assets/446bfb6c-8eab-4a2c-a622-dce1ac33cca6)

**Comment by testnet0** [comment]
![image](https://github.com/user-attachments/assets/f328acc8-8708-44d3-a4cf-a15469bac1bc)
看下httpx版本号是否正确

**Comment by gslsf223** [comment]
![image](https://github.com/user-attachments/assets/acaaeb4e-9804-4a3e-844e-f1b3cf543f14)
感觉安装了一个假的。。
