### ISSUE TITLE
漏洞扫描无法使用

### ISSUE THREAD

**Issue by minghuinet** [testnet0/testnet#33]
已安装nuclei、Xpoc、afrog，运行时提示不存在，容器内已确认安装了
![image](https://github.com/user-attachments/assets/c3d995e1-9370-4df7-9634-bf5c1affd9e8)
![image](https://github.com/user-attachments/assets/7ac7f295-f121-4bce-859f-75edb54c8ce9)

**Comment by sssectest** [comment]
你好，脚本列表里的有没有删除过

**Comment by testnet0** [comment]
你好，截图看下工作流管理-脚本列表

**Comment by testnet0** [comment]
docker-compose logs testnet-client
