### ISSUE TITLE
使用模板导入IP时有ip数量限制

### ISSUE THREAD

**Issue by foxwood16** [testnet0/testnet#34]
![屏幕截图 2024-11-30 115902](https://github.com/user-attachments/assets/f42a4ba9-cd51-43de-b83d-10d072bcb410)
文件导入失败:org.jeecg.modules.testnet.server.mapper.asset.AssetIpMapper.insert (batch index #1) failed. Cause: java.sql.BatchUpdateException: Data truncation: Data too long for column 'ip' at row 1\n; Data truncation: Data too long for column 'ip' at row 1; nested exception is java.sql.BatchUpdateException: Data truncation: Data too long for column 'ip' at row 1
一次导入IP数量的限制是多少？

**Comment by testnet0** [comment]
检查下IP格式是否正确呢，目前最大支持32位

**Comment by foxwood16** [comment]
IP格式都是正确的，拆分后多次导入是可以的，但是当导入2000个IP后，再通过模板导入会提示有重复ip，只能再拆得小一点才能成功导入。IP列都是通过excel删除重复值的。

**Comment by testnet0** [comment]
未复现
