### ISSUE TITLE
验证码网络错误，已经等了一天多了

### ISSUE THREAD

**Issue by o-zero-o** [testnet0/testnet#4]
![PixPin_2024-07-24_09-29-19](https://github.com/user-attachments/assets/537f84d8-4d86-4d0e-be77-b9a729c610b7)
![PixPin_2024-07-24_09-28-42](https://github.com/user-attachments/assets/3ad02d90-9acb-412e-80af-d127784276e7)

**Comment by testnet0** [comment]
删除目录重新安装一下
