### ISSUE TITLE
分布式部署问题

### ISSUE THREAD

**Issue by flowerPanda1** [testnet0/testnet#40]
我已经添加了客户端ip跟名字，但还是一直提示没设置问题

**Comment by testnet0** [comment]
请截图下配置

**Comment by flowerPanda1** [comment]
![image](https://github.com/user-attachments/assets/9fc0f8fd-8361-4cc5-ab58-95e7bacb46f1)
![image](https://github.com/user-attachments/assets/fa0a50a1-af31-4d32-9267-a6398ce43221)
![微信截图_20241210135451](https://github.com/user-attachments/assets/443ac871-876f-4795-8b38-13c55bbe224c)

**Comment by testnet0** [comment]
IP需要大写

**Comment by flowerPanda1** [comment]
IP大写还是不行，我换了另一台搭建可以了，资产要是1w个的话可以一键导出吗，还是只能500一页来导出

**Comment by testnet0** [comment]
https://testnet.shengkai.wang/guide/%E8%B5%84%E4%BA%A7%E7%AE%A1%E7%90%86.html#%E5%AF%BC%E5%87%BA%E8%B5%84%E4%BA%A7
